/**
 * One-shot Option B migration: move connected accounts into the v2 model with
 * ENCRYPTED credentials, and preserve only explicit user INTENT (VIPs,
 * corrections, sender teachings, interests, hand-named matters, closures).
 *
 * It deliberately does NOT copy inferred reads, people tiers, relationships,
 * briefs, digest themes, or auto-clustered matter assignments — those are
 * regenerated by reading the mailbox.
 *
 * Usage:
 *   tsx scripts/migrate-v2-accounts.mts --dry-run   # counts only, no secrets
 *   tsx scripts/migrate-v2-accounts.mts             # writes to Postgres
 *
 * The legacy store is read through the existing KV facade (Redis in prod).
 * Writing requires POSTGRES_URL / SEER_V2_DATABASE_URL.
 */
import kv from "../src/lib/store/kv.ts";
import {
  upsertUser,
  upsertAccount,
  saveCredentials,
} from "../src/lib/v2/db/accounts.ts";
import {
  applyPreservedIntent,
  countPreservedIntent,
  type PreservedIntent,
} from "../src/lib/v2/db/intent.ts";
import { collectPeople, seedPeople } from "../src/lib/v2/db/seed-relationships.ts";
import type { StoredAccount } from "../src/lib/store/accounts.ts";
import type { MatterEdits } from "../src/lib/store/manual-matters.ts";

const { kvGet, accountKey } = kv as unknown as {
  kvGet: <T>(key: string) => Promise<T | null>;
  accountKey: (email: string) => string;
};

const dryRun = process.argv.includes("--dry-run");

/**
 * Legacy OAuth expiry is stored in SECONDS (NextAuth convention); v2 works in
 * milliseconds. Normalize so a migrated token isn't written as expired in 1970.
 */
function epochMs(value: number | undefined): number | undefined {
  if (!value) return undefined;
  return value < 1e12 ? value * 1000 : value;
}

async function readIntent(email: string): Promise<PreservedIntent> {
  const key = accountKey(email);
  const people =
    (await kvGet<Record<string, { email: string; name?: string; vip?: boolean }>>(
      `people:${key}`,
    )) ?? {};
  const overrides =
    (await kvGet<Record<string, string>>("sender-overrides")) ?? {};
  const edits = (await kvGet<MatterEdits>(`matter-edits:${key}`)) ?? {
    renames: {},
    manual: [],
  };

  const vips = Object.values(people)
    .filter((p) => p.vip)
    .map((p) => ({ email: p.email, name: p.name }));

  // Sender overrides are the only explicit sender teachings we keep.
  const senderTeachings = Object.entries(overrides).map(([email, action]) => ({
    email,
    action,
  }));

  const manualMatters = (edits.manual ?? []).map((m) => ({
    title: m.title,
    orgUnit: m.orgUnit,
    // Legacy manual matters carry message ids, not conversation ids; the
    // rebuild re-links them once conversations exist. We keep the titles as
    // ground truth here and leave linking to the corpus rebuild.
    conversationProviderIds: [] as string[],
  }));

  return {
    vips,
    corrections: [],
    senderTeachings,
    interests: [],
    manualMatters,
    closures: [],
  };
}

async function main() {
  const store = await kvGet<{ accounts: StoredAccount[] }>("accounts");
  const accounts = store?.accounts ?? [];
  if (accounts.length === 0) {
    console.log("No legacy accounts found.");
    return;
  }

  for (const acct of accounts) {
    const intent = await readIntent(acct.email);
    const counts = countPreservedIntent(intent);
    if (dryRun) {
      console.log(
        `[dry-run] ${acct.provider}:${acct.email} preserve=${JSON.stringify(counts)} ` +
          `(credentials: ${acct.refreshToken ? "present" : "none"})`,
      );
      continue;
    }

    const provider = acct.provider === "google" ? "google" : "microsoft";
    const userId = await upsertUser(acct.email);
    const accountId = await upsertAccount({
      userId,
      provider,
      email: acct.email,
      displayName: acct.name,
    });
    await saveCredentials(accountId, provider, {
      accessToken: acct.accessToken,
      refreshToken: acct.refreshToken,
      expiresAt: epochMs(acct.expiresAt),
    });
    const applied = await applyPreservedIntent(accountId, intent);

    // Seed the relationship graph so the read pipeline protects real humans
    // from the first tick, not after it has learned them the hard way.
    const key = acct.email.toLowerCase().trim();
    const [people, history, personal] = await Promise.all([
      kvGet<Record<string, { tier?: string; vip?: boolean; name?: string }>>(`people:${key}`),
      kvGet<{ history?: { contacts?: Record<string, { sentTo?: number }> }; contacts?: Record<string, { sentTo?: number }> }>(`mail-history:${key}`),
      kvGet<{ contacts?: string[] }>(`personal:${key}`),
    ]);
    const seeded = await seedPeople(
      accountId,
      collectPeople({
        people: people ?? null,
        history: history?.history ?? history ?? null,
        contacts: personal?.contacts ?? null,
      }),
    );

    console.log(
      `migrated ${acct.provider}:${acct.email} preserved=${JSON.stringify(applied)} people=${seeded}`,
    );
  }
}

main().catch((e) => {
  console.error("migration failed:", e instanceof Error ? e.message : e);
  process.exit(1);
});
